// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: com/digitalasset/canton/protocol/v0/causality.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CausalityMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetDomainId string                 `protobuf:"bytes,1,opt,name=target_domain_id,json=targetDomainId,proto3" json:"target_domain_id,omitempty"`
	TransferId     *TransferId            `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Clock          *VectorClock           `protobuf:"bytes,3,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CausalityMessage) Reset() {
	*x = CausalityMessage{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalityMessage) ProtoMessage() {}

func (x *CausalityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalityMessage.ProtoReflect.Descriptor instead.
func (*CausalityMessage) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{0}
}

func (x *CausalityMessage) GetTargetDomainId() string {
	if x != nil {
		return x.TargetDomainId
	}
	return ""
}

func (x *CausalityMessage) GetTransferId() *TransferId {
	if x != nil {
		return x.TransferId
	}
	return nil
}

func (x *CausalityMessage) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

type VectorClock struct {
	state          protoimpl.MessageState            `protogen:"open.v1"`
	OriginDomainId string                            `protobuf:"bytes,1,opt,name=origin_domain_id,json=originDomainId,proto3" json:"origin_domain_id,omitempty"`
	LocalTs        *timestamppb.Timestamp            `protobuf:"bytes,2,opt,name=local_ts,json=localTs,proto3" json:"local_ts,omitempty"`
	PartyId        string                            `protobuf:"bytes,4,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Clock          map[string]*timestamppb.Timestamp `protobuf:"bytes,5,rep,name=clock,proto3" json:"clock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{1}
}

func (x *VectorClock) GetOriginDomainId() string {
	if x != nil {
		return x.OriginDomainId
	}
	return ""
}

func (x *VectorClock) GetLocalTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LocalTs
	}
	return nil
}

func (x *VectorClock) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *VectorClock) GetClock() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.Clock
	}
	return nil
}

type CausalityUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InformeeStakeholders []string               `protobuf:"bytes,1,rep,name=informeeStakeholders,proto3" json:"informeeStakeholders,omitempty"`
	Ts                   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	DomainId             string                 `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	RequestCounter       int64                  `protobuf:"varint,4,opt,name=request_counter,json=requestCounter,proto3" json:"request_counter,omitempty"`
	// Types that are valid to be assigned to Tag:
	//
	//	*CausalityUpdate_TransactionUpdate
	//	*CausalityUpdate_TransferOutUpdate
	//	*CausalityUpdate_TransferInUpdate
	Tag           isCausalityUpdate_Tag `protobuf_oneof:"tag"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CausalityUpdate) Reset() {
	*x = CausalityUpdate{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CausalityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CausalityUpdate) ProtoMessage() {}

func (x *CausalityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CausalityUpdate.ProtoReflect.Descriptor instead.
func (*CausalityUpdate) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{2}
}

func (x *CausalityUpdate) GetInformeeStakeholders() []string {
	if x != nil {
		return x.InformeeStakeholders
	}
	return nil
}

func (x *CausalityUpdate) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *CausalityUpdate) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *CausalityUpdate) GetRequestCounter() int64 {
	if x != nil {
		return x.RequestCounter
	}
	return 0
}

func (x *CausalityUpdate) GetTag() isCausalityUpdate_Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *CausalityUpdate) GetTransactionUpdate() *TransactionUpdate {
	if x != nil {
		if x, ok := x.Tag.(*CausalityUpdate_TransactionUpdate); ok {
			return x.TransactionUpdate
		}
	}
	return nil
}

func (x *CausalityUpdate) GetTransferOutUpdate() *TransferOutUpdate {
	if x != nil {
		if x, ok := x.Tag.(*CausalityUpdate_TransferOutUpdate); ok {
			return x.TransferOutUpdate
		}
	}
	return nil
}

func (x *CausalityUpdate) GetTransferInUpdate() *TransferInUpdate {
	if x != nil {
		if x, ok := x.Tag.(*CausalityUpdate_TransferInUpdate); ok {
			return x.TransferInUpdate
		}
	}
	return nil
}

type isCausalityUpdate_Tag interface {
	isCausalityUpdate_Tag()
}

type CausalityUpdate_TransactionUpdate struct {
	TransactionUpdate *TransactionUpdate `protobuf:"bytes,5,opt,name=transactionUpdate,proto3,oneof"`
}

type CausalityUpdate_TransferOutUpdate struct {
	TransferOutUpdate *TransferOutUpdate `protobuf:"bytes,6,opt,name=transferOutUpdate,proto3,oneof"`
}

type CausalityUpdate_TransferInUpdate struct {
	TransferInUpdate *TransferInUpdate `protobuf:"bytes,7,opt,name=transferInUpdate,proto3,oneof"`
}

func (*CausalityUpdate_TransactionUpdate) isCausalityUpdate_Tag() {}

func (*CausalityUpdate_TransferOutUpdate) isCausalityUpdate_Tag() {}

func (*CausalityUpdate_TransferInUpdate) isCausalityUpdate_Tag() {}

type TransactionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionUpdate) Reset() {
	*x = TransactionUpdate{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionUpdate) ProtoMessage() {}

func (x *TransactionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionUpdate.ProtoReflect.Descriptor instead.
func (*TransactionUpdate) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{3}
}

type TransferOutUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    *TransferId            `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOutUpdate) Reset() {
	*x = TransferOutUpdate{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOutUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOutUpdate) ProtoMessage() {}

func (x *TransferOutUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOutUpdate.ProtoReflect.Descriptor instead.
func (*TransferOutUpdate) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{4}
}

func (x *TransferOutUpdate) GetTransferId() *TransferId {
	if x != nil {
		return x.TransferId
	}
	return nil
}

type TransferInUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    *TransferId            `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferInUpdate) Reset() {
	*x = TransferInUpdate{}
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferInUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInUpdate) ProtoMessage() {}

func (x *TransferInUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInUpdate.ProtoReflect.Descriptor instead.
func (*TransferInUpdate) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP(), []int{5}
}

func (x *TransferInUpdate) GetTransferId() *TransferId {
	if x != nil {
		return x.TransferId
	}
	return nil
}

var File_com_digitalasset_canton_protocol_v0_causality_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_protocol_v0_causality_proto_rawDesc = "" +
	"\n" +
	"3com/digitalasset/canton/protocol/v0/causality.proto\x12#com.digitalasset.canton.protocol.v0\x1a>com/digitalasset/canton/protocol/v0/participant_transfer.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x10CausalityMessage\x12(\n" +
	"\x10target_domain_id\x18\x01 \x01(\tR\x0etargetDomainId\x12P\n" +
	"\vtransfer_id\x18\x02 \x01(\v2/.com.digitalasset.canton.protocol.v0.TransferIdR\n" +
	"transferId\x12F\n" +
	"\x05clock\x18\x03 \x01(\v20.com.digitalasset.canton.protocol.v0.VectorClockR\x05clock\"\xb2\x02\n" +
	"\vVectorClock\x12(\n" +
	"\x10origin_domain_id\x18\x01 \x01(\tR\x0eoriginDomainId\x125\n" +
	"\blocal_ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\alocalTs\x12\x19\n" +
	"\bparty_id\x18\x04 \x01(\tR\apartyId\x12Q\n" +
	"\x05clock\x18\x05 \x03(\v2;.com.digitalasset.canton.protocol.v0.VectorClock.ClockEntryR\x05clock\x1aT\n" +
	"\n" +
	"ClockEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\"\xf3\x03\n" +
	"\x0fCausalityUpdate\x122\n" +
	"\x14informeeStakeholders\x18\x01 \x03(\tR\x14informeeStakeholders\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1b\n" +
	"\tdomain_id\x18\x03 \x01(\tR\bdomainId\x12'\n" +
	"\x0frequest_counter\x18\x04 \x01(\x03R\x0erequestCounter\x12f\n" +
	"\x11transactionUpdate\x18\x05 \x01(\v26.com.digitalasset.canton.protocol.v0.TransactionUpdateH\x00R\x11transactionUpdate\x12f\n" +
	"\x11transferOutUpdate\x18\x06 \x01(\v26.com.digitalasset.canton.protocol.v0.TransferOutUpdateH\x00R\x11transferOutUpdate\x12c\n" +
	"\x10transferInUpdate\x18\a \x01(\v25.com.digitalasset.canton.protocol.v0.TransferInUpdateH\x00R\x10transferInUpdateB\x05\n" +
	"\x03tag\"\x13\n" +
	"\x11TransactionUpdate\"e\n" +
	"\x11TransferOutUpdate\x12P\n" +
	"\vtransfer_id\x18\x01 \x01(\v2/.com.digitalasset.canton.protocol.v0.TransferIdR\n" +
	"transferId\"d\n" +
	"\x10TransferInUpdate\x12P\n" +
	"\vtransfer_id\x18\x01 \x01(\v2/.com.digitalasset.canton.protocol.v0.TransferIdR\n" +
	"transferIdBTZRgithub.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/protocol/v0b\x06proto3"

var (
	file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescData []byte
)

func file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v0_causality_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v0_causality_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_protocol_v0_causality_proto_rawDescData
}

var file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_digitalasset_canton_protocol_v0_causality_proto_goTypes = []any{
	(*CausalityMessage)(nil),      // 0: com.digitalasset.canton.protocol.v0.CausalityMessage
	(*VectorClock)(nil),           // 1: com.digitalasset.canton.protocol.v0.VectorClock
	(*CausalityUpdate)(nil),       // 2: com.digitalasset.canton.protocol.v0.CausalityUpdate
	(*TransactionUpdate)(nil),     // 3: com.digitalasset.canton.protocol.v0.TransactionUpdate
	(*TransferOutUpdate)(nil),     // 4: com.digitalasset.canton.protocol.v0.TransferOutUpdate
	(*TransferInUpdate)(nil),      // 5: com.digitalasset.canton.protocol.v0.TransferInUpdate
	nil,                           // 6: com.digitalasset.canton.protocol.v0.VectorClock.ClockEntry
	(*TransferId)(nil),            // 7: com.digitalasset.canton.protocol.v0.TransferId
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_com_digitalasset_canton_protocol_v0_causality_proto_depIdxs = []int32{
	7,  // 0: com.digitalasset.canton.protocol.v0.CausalityMessage.transfer_id:type_name -> com.digitalasset.canton.protocol.v0.TransferId
	1,  // 1: com.digitalasset.canton.protocol.v0.CausalityMessage.clock:type_name -> com.digitalasset.canton.protocol.v0.VectorClock
	8,  // 2: com.digitalasset.canton.protocol.v0.VectorClock.local_ts:type_name -> google.protobuf.Timestamp
	6,  // 3: com.digitalasset.canton.protocol.v0.VectorClock.clock:type_name -> com.digitalasset.canton.protocol.v0.VectorClock.ClockEntry
	8,  // 4: com.digitalasset.canton.protocol.v0.CausalityUpdate.ts:type_name -> google.protobuf.Timestamp
	3,  // 5: com.digitalasset.canton.protocol.v0.CausalityUpdate.transactionUpdate:type_name -> com.digitalasset.canton.protocol.v0.TransactionUpdate
	4,  // 6: com.digitalasset.canton.protocol.v0.CausalityUpdate.transferOutUpdate:type_name -> com.digitalasset.canton.protocol.v0.TransferOutUpdate
	5,  // 7: com.digitalasset.canton.protocol.v0.CausalityUpdate.transferInUpdate:type_name -> com.digitalasset.canton.protocol.v0.TransferInUpdate
	7,  // 8: com.digitalasset.canton.protocol.v0.TransferOutUpdate.transfer_id:type_name -> com.digitalasset.canton.protocol.v0.TransferId
	7,  // 9: com.digitalasset.canton.protocol.v0.TransferInUpdate.transfer_id:type_name -> com.digitalasset.canton.protocol.v0.TransferId
	8,  // 10: com.digitalasset.canton.protocol.v0.VectorClock.ClockEntry.value:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_protocol_v0_causality_proto_init() }
func file_com_digitalasset_canton_protocol_v0_causality_proto_init() {
	if File_com_digitalasset_canton_protocol_v0_causality_proto != nil {
		return
	}
	file_com_digitalasset_canton_protocol_v0_participant_transfer_proto_init()
	file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes[2].OneofWrappers = []any{
		(*CausalityUpdate_TransactionUpdate)(nil),
		(*CausalityUpdate_TransferOutUpdate)(nil),
		(*CausalityUpdate_TransferInUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v0_causality_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v0_causality_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_digitalasset_canton_protocol_v0_causality_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_protocol_v0_causality_proto_depIdxs,
		MessageInfos:      file_com_digitalasset_canton_protocol_v0_causality_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_protocol_v0_causality_proto = out.File
	file_com_digitalasset_canton_protocol_v0_causality_proto_goTypes = nil
	file_com_digitalasset_canton_protocol_v0_causality_proto_depIdxs = nil
}
