// Copyright (c) 2017-2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: com/digitalasset/canton/domain/admin/v0/enterprise_mediator_administration_service.proto

package v0

import (
	context "context"
	v0 "github.com/digital-asset/dazl-client/v7/go/api/com/digitalasset/canton/pruning/admin/v0"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EnterpriseMediatorAdministrationService_Prune_FullMethodName                  = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/Prune"
	EnterpriseMediatorAdministrationService_SetSchedule_FullMethodName            = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/SetSchedule"
	EnterpriseMediatorAdministrationService_SetCron_FullMethodName                = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/SetCron"
	EnterpriseMediatorAdministrationService_SetMaxDuration_FullMethodName         = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/SetMaxDuration"
	EnterpriseMediatorAdministrationService_SetRetention_FullMethodName           = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/SetRetention"
	EnterpriseMediatorAdministrationService_ClearSchedule_FullMethodName          = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/ClearSchedule"
	EnterpriseMediatorAdministrationService_GetSchedule_FullMethodName            = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/GetSchedule"
	EnterpriseMediatorAdministrationService_LocatePruningTimestamp_FullMethodName = "/com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService/LocatePruningTimestamp"
)

// EnterpriseMediatorAdministrationServiceClient is the client API for EnterpriseMediatorAdministrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnterpriseMediatorAdministrationServiceClient interface {
	Prune(ctx context.Context, in *MediatorPruningRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetSchedule(ctx context.Context, in *v0.SetSchedule_Request, opts ...grpc.CallOption) (*v0.SetSchedule_Response, error)
	SetCron(ctx context.Context, in *v0.SetCron_Request, opts ...grpc.CallOption) (*v0.SetCron_Response, error)
	SetMaxDuration(ctx context.Context, in *v0.SetMaxDuration_Request, opts ...grpc.CallOption) (*v0.SetMaxDuration_Response, error)
	SetRetention(ctx context.Context, in *v0.SetRetention_Request, opts ...grpc.CallOption) (*v0.SetRetention_Response, error)
	ClearSchedule(ctx context.Context, in *v0.ClearSchedule_Request, opts ...grpc.CallOption) (*v0.ClearSchedule_Response, error)
	GetSchedule(ctx context.Context, in *v0.GetSchedule_Request, opts ...grpc.CallOption) (*v0.GetSchedule_Response, error)
	LocatePruningTimestamp(ctx context.Context, in *v0.LocatePruningTimestamp_Request, opts ...grpc.CallOption) (*v0.LocatePruningTimestamp_Response, error)
}

type enterpriseMediatorAdministrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnterpriseMediatorAdministrationServiceClient(cc grpc.ClientConnInterface) EnterpriseMediatorAdministrationServiceClient {
	return &enterpriseMediatorAdministrationServiceClient{cc}
}

func (c *enterpriseMediatorAdministrationServiceClient) Prune(ctx context.Context, in *MediatorPruningRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) SetSchedule(ctx context.Context, in *v0.SetSchedule_Request, opts ...grpc.CallOption) (*v0.SetSchedule_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.SetSchedule_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_SetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) SetCron(ctx context.Context, in *v0.SetCron_Request, opts ...grpc.CallOption) (*v0.SetCron_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.SetCron_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_SetCron_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) SetMaxDuration(ctx context.Context, in *v0.SetMaxDuration_Request, opts ...grpc.CallOption) (*v0.SetMaxDuration_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.SetMaxDuration_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_SetMaxDuration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) SetRetention(ctx context.Context, in *v0.SetRetention_Request, opts ...grpc.CallOption) (*v0.SetRetention_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.SetRetention_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_SetRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) ClearSchedule(ctx context.Context, in *v0.ClearSchedule_Request, opts ...grpc.CallOption) (*v0.ClearSchedule_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.ClearSchedule_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_ClearSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) GetSchedule(ctx context.Context, in *v0.GetSchedule_Request, opts ...grpc.CallOption) (*v0.GetSchedule_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.GetSchedule_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enterpriseMediatorAdministrationServiceClient) LocatePruningTimestamp(ctx context.Context, in *v0.LocatePruningTimestamp_Request, opts ...grpc.CallOption) (*v0.LocatePruningTimestamp_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v0.LocatePruningTimestamp_Response)
	err := c.cc.Invoke(ctx, EnterpriseMediatorAdministrationService_LocatePruningTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnterpriseMediatorAdministrationServiceServer is the server API for EnterpriseMediatorAdministrationService service.
// All implementations must embed UnimplementedEnterpriseMediatorAdministrationServiceServer
// for forward compatibility
type EnterpriseMediatorAdministrationServiceServer interface {
	Prune(context.Context, *MediatorPruningRequest) (*emptypb.Empty, error)
	SetSchedule(context.Context, *v0.SetSchedule_Request) (*v0.SetSchedule_Response, error)
	SetCron(context.Context, *v0.SetCron_Request) (*v0.SetCron_Response, error)
	SetMaxDuration(context.Context, *v0.SetMaxDuration_Request) (*v0.SetMaxDuration_Response, error)
	SetRetention(context.Context, *v0.SetRetention_Request) (*v0.SetRetention_Response, error)
	ClearSchedule(context.Context, *v0.ClearSchedule_Request) (*v0.ClearSchedule_Response, error)
	GetSchedule(context.Context, *v0.GetSchedule_Request) (*v0.GetSchedule_Response, error)
	LocatePruningTimestamp(context.Context, *v0.LocatePruningTimestamp_Request) (*v0.LocatePruningTimestamp_Response, error)
	mustEmbedUnimplementedEnterpriseMediatorAdministrationServiceServer()
}

// UnimplementedEnterpriseMediatorAdministrationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnterpriseMediatorAdministrationServiceServer struct {
}

func (UnimplementedEnterpriseMediatorAdministrationServiceServer) Prune(context.Context, *MediatorPruningRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) SetSchedule(context.Context, *v0.SetSchedule_Request) (*v0.SetSchedule_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSchedule not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) SetCron(context.Context, *v0.SetCron_Request) (*v0.SetCron_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCron not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) SetMaxDuration(context.Context, *v0.SetMaxDuration_Request) (*v0.SetMaxDuration_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMaxDuration not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) SetRetention(context.Context, *v0.SetRetention_Request) (*v0.SetRetention_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRetention not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) ClearSchedule(context.Context, *v0.ClearSchedule_Request) (*v0.ClearSchedule_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSchedule not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) GetSchedule(context.Context, *v0.GetSchedule_Request) (*v0.GetSchedule_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) LocatePruningTimestamp(context.Context, *v0.LocatePruningTimestamp_Request) (*v0.LocatePruningTimestamp_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocatePruningTimestamp not implemented")
}
func (UnimplementedEnterpriseMediatorAdministrationServiceServer) mustEmbedUnimplementedEnterpriseMediatorAdministrationServiceServer() {
}

// UnsafeEnterpriseMediatorAdministrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnterpriseMediatorAdministrationServiceServer will
// result in compilation errors.
type UnsafeEnterpriseMediatorAdministrationServiceServer interface {
	mustEmbedUnimplementedEnterpriseMediatorAdministrationServiceServer()
}

func RegisterEnterpriseMediatorAdministrationServiceServer(s grpc.ServiceRegistrar, srv EnterpriseMediatorAdministrationServiceServer) {
	s.RegisterService(&EnterpriseMediatorAdministrationService_ServiceDesc, srv)
}

func _EnterpriseMediatorAdministrationService_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediatorPruningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).Prune(ctx, req.(*MediatorPruningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_SetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.SetSchedule_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_SetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetSchedule(ctx, req.(*v0.SetSchedule_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_SetCron_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.SetCron_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetCron(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_SetCron_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetCron(ctx, req.(*v0.SetCron_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_SetMaxDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.SetMaxDuration_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetMaxDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_SetMaxDuration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetMaxDuration(ctx, req.(*v0.SetMaxDuration_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_SetRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.SetRetention_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_SetRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).SetRetention(ctx, req.(*v0.SetRetention_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_ClearSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.ClearSchedule_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).ClearSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_ClearSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).ClearSchedule(ctx, req.(*v0.ClearSchedule_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.GetSchedule_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).GetSchedule(ctx, req.(*v0.GetSchedule_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnterpriseMediatorAdministrationService_LocatePruningTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v0.LocatePruningTimestamp_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnterpriseMediatorAdministrationServiceServer).LocatePruningTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnterpriseMediatorAdministrationService_LocatePruningTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnterpriseMediatorAdministrationServiceServer).LocatePruningTimestamp(ctx, req.(*v0.LocatePruningTimestamp_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// EnterpriseMediatorAdministrationService_ServiceDesc is the grpc.ServiceDesc for EnterpriseMediatorAdministrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnterpriseMediatorAdministrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.digitalasset.canton.domain.admin.v0.EnterpriseMediatorAdministrationService",
	HandlerType: (*EnterpriseMediatorAdministrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prune",
			Handler:    _EnterpriseMediatorAdministrationService_Prune_Handler,
		},
		{
			MethodName: "SetSchedule",
			Handler:    _EnterpriseMediatorAdministrationService_SetSchedule_Handler,
		},
		{
			MethodName: "SetCron",
			Handler:    _EnterpriseMediatorAdministrationService_SetCron_Handler,
		},
		{
			MethodName: "SetMaxDuration",
			Handler:    _EnterpriseMediatorAdministrationService_SetMaxDuration_Handler,
		},
		{
			MethodName: "SetRetention",
			Handler:    _EnterpriseMediatorAdministrationService_SetRetention_Handler,
		},
		{
			MethodName: "ClearSchedule",
			Handler:    _EnterpriseMediatorAdministrationService_ClearSchedule_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _EnterpriseMediatorAdministrationService_GetSchedule_Handler,
		},
		{
			MethodName: "LocatePruningTimestamp",
			Handler:    _EnterpriseMediatorAdministrationService_LocatePruningTimestamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/digitalasset/canton/domain/admin/v0/enterprise_mediator_administration_service.proto",
}
