// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: com/digitalasset/canton/protocol/v30/synchronization.proto

package v30

import (
	v30 "github.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/crypto/v30"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypedSignedProtocolMessageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SomeSignedProtocolMessage:
	//
	//	*TypedSignedProtocolMessageContent_ConfirmationResponses
	//	*TypedSignedProtocolMessageContent_ConfirmationResult
	//	*TypedSignedProtocolMessageContent_AcsCommitment
	//	*TypedSignedProtocolMessageContent_SetTrafficPurchased
	SomeSignedProtocolMessage isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage `protobuf_oneof:"some_signed_protocol_message"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TypedSignedProtocolMessageContent) Reset() {
	*x = TypedSignedProtocolMessageContent{}
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedSignedProtocolMessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedSignedProtocolMessageContent) ProtoMessage() {}

func (x *TypedSignedProtocolMessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedSignedProtocolMessageContent.ProtoReflect.Descriptor instead.
func (*TypedSignedProtocolMessageContent) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescGZIP(), []int{0}
}

func (x *TypedSignedProtocolMessageContent) GetSomeSignedProtocolMessage() isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage {
	if x != nil {
		return x.SomeSignedProtocolMessage
	}
	return nil
}

func (x *TypedSignedProtocolMessageContent) GetConfirmationResponses() []byte {
	if x != nil {
		if x, ok := x.SomeSignedProtocolMessage.(*TypedSignedProtocolMessageContent_ConfirmationResponses); ok {
			return x.ConfirmationResponses
		}
	}
	return nil
}

func (x *TypedSignedProtocolMessageContent) GetConfirmationResult() []byte {
	if x != nil {
		if x, ok := x.SomeSignedProtocolMessage.(*TypedSignedProtocolMessageContent_ConfirmationResult); ok {
			return x.ConfirmationResult
		}
	}
	return nil
}

func (x *TypedSignedProtocolMessageContent) GetAcsCommitment() []byte {
	if x != nil {
		if x, ok := x.SomeSignedProtocolMessage.(*TypedSignedProtocolMessageContent_AcsCommitment); ok {
			return x.AcsCommitment
		}
	}
	return nil
}

func (x *TypedSignedProtocolMessageContent) GetSetTrafficPurchased() []byte {
	if x != nil {
		if x, ok := x.SomeSignedProtocolMessage.(*TypedSignedProtocolMessageContent_SetTrafficPurchased); ok {
			return x.SetTrafficPurchased
		}
	}
	return nil
}

type isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage interface {
	isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage()
}

type TypedSignedProtocolMessageContent_ConfirmationResponses struct {
	ConfirmationResponses []byte `protobuf:"bytes,2,opt,name=confirmation_responses,json=confirmationResponses,proto3,oneof"`
}

type TypedSignedProtocolMessageContent_ConfirmationResult struct {
	ConfirmationResult []byte `protobuf:"bytes,3,opt,name=confirmation_result,json=confirmationResult,proto3,oneof"`
}

type TypedSignedProtocolMessageContent_AcsCommitment struct {
	AcsCommitment []byte `protobuf:"bytes,4,opt,name=acs_commitment,json=acsCommitment,proto3,oneof"`
}

type TypedSignedProtocolMessageContent_SetTrafficPurchased struct {
	SetTrafficPurchased []byte `protobuf:"bytes,5,opt,name=set_traffic_purchased,json=setTrafficPurchased,proto3,oneof"`
}

func (*TypedSignedProtocolMessageContent_ConfirmationResponses) isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage() {
}

func (*TypedSignedProtocolMessageContent_ConfirmationResult) isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage() {
}

func (*TypedSignedProtocolMessageContent_AcsCommitment) isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage() {
}

func (*TypedSignedProtocolMessageContent_SetTrafficPurchased) isTypedSignedProtocolMessageContent_SomeSignedProtocolMessage() {
}

type SignedProtocolMessage struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	Signature                         []*v30.Signature       `protobuf:"bytes,1,rep,name=signature,proto3" json:"signature,omitempty"`
	TypedSignedProtocolMessageContent []byte                 `protobuf:"bytes,2,opt,name=typed_signed_protocol_message_content,json=typedSignedProtocolMessageContent,proto3" json:"typed_signed_protocol_message_content,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *SignedProtocolMessage) Reset() {
	*x = SignedProtocolMessage{}
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedProtocolMessage) ProtoMessage() {}

func (x *SignedProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedProtocolMessage.ProtoReflect.Descriptor instead.
func (*SignedProtocolMessage) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescGZIP(), []int{1}
}

func (x *SignedProtocolMessage) GetSignature() []*v30.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedProtocolMessage) GetTypedSignedProtocolMessageContent() []byte {
	if x != nil {
		return x.TypedSignedProtocolMessageContent
	}
	return nil
}

type EnvelopeContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SomeEnvelopeContent:
	//
	//	*EnvelopeContent_InformeeMessage
	//	*EnvelopeContent_EncryptedViewMessage
	//	*EnvelopeContent_UnassignmentMediatorMessage
	//	*EnvelopeContent_AssignmentMediatorMessage
	//	*EnvelopeContent_RootHashMessage
	//	*EnvelopeContent_TopologyTransactionsBroadcast
	SomeEnvelopeContent isEnvelopeContent_SomeEnvelopeContent `protobuf_oneof:"some_envelope_content"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnvelopeContent) Reset() {
	*x = EnvelopeContent{}
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeContent) ProtoMessage() {}

func (x *EnvelopeContent) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeContent.ProtoReflect.Descriptor instead.
func (*EnvelopeContent) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescGZIP(), []int{2}
}

func (x *EnvelopeContent) GetSomeEnvelopeContent() isEnvelopeContent_SomeEnvelopeContent {
	if x != nil {
		return x.SomeEnvelopeContent
	}
	return nil
}

func (x *EnvelopeContent) GetInformeeMessage() *InformeeMessage {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_InformeeMessage); ok {
			return x.InformeeMessage
		}
	}
	return nil
}

func (x *EnvelopeContent) GetEncryptedViewMessage() *EncryptedViewMessage {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_EncryptedViewMessage); ok {
			return x.EncryptedViewMessage
		}
	}
	return nil
}

func (x *EnvelopeContent) GetUnassignmentMediatorMessage() *UnassignmentMediatorMessage {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_UnassignmentMediatorMessage); ok {
			return x.UnassignmentMediatorMessage
		}
	}
	return nil
}

func (x *EnvelopeContent) GetAssignmentMediatorMessage() *AssignmentMediatorMessage {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_AssignmentMediatorMessage); ok {
			return x.AssignmentMediatorMessage
		}
	}
	return nil
}

func (x *EnvelopeContent) GetRootHashMessage() *RootHashMessage {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_RootHashMessage); ok {
			return x.RootHashMessage
		}
	}
	return nil
}

func (x *EnvelopeContent) GetTopologyTransactionsBroadcast() *TopologyTransactionsBroadcast {
	if x != nil {
		if x, ok := x.SomeEnvelopeContent.(*EnvelopeContent_TopologyTransactionsBroadcast); ok {
			return x.TopologyTransactionsBroadcast
		}
	}
	return nil
}

type isEnvelopeContent_SomeEnvelopeContent interface {
	isEnvelopeContent_SomeEnvelopeContent()
}

type EnvelopeContent_InformeeMessage struct {
	InformeeMessage *InformeeMessage `protobuf:"bytes,1,opt,name=informee_message,json=informeeMessage,proto3,oneof"`
}

type EnvelopeContent_EncryptedViewMessage struct {
	EncryptedViewMessage *EncryptedViewMessage `protobuf:"bytes,2,opt,name=encrypted_view_message,json=encryptedViewMessage,proto3,oneof"`
}

type EnvelopeContent_UnassignmentMediatorMessage struct {
	UnassignmentMediatorMessage *UnassignmentMediatorMessage `protobuf:"bytes,3,opt,name=unassignment_mediator_message,json=unassignmentMediatorMessage,proto3,oneof"`
}

type EnvelopeContent_AssignmentMediatorMessage struct {
	AssignmentMediatorMessage *AssignmentMediatorMessage `protobuf:"bytes,4,opt,name=assignment_mediator_message,json=assignmentMediatorMessage,proto3,oneof"`
}

type EnvelopeContent_RootHashMessage struct {
	RootHashMessage *RootHashMessage `protobuf:"bytes,5,opt,name=root_hash_message,json=rootHashMessage,proto3,oneof"`
}

type EnvelopeContent_TopologyTransactionsBroadcast struct {
	TopologyTransactionsBroadcast *TopologyTransactionsBroadcast `protobuf:"bytes,6,opt,name=topology_transactions_broadcast,json=topologyTransactionsBroadcast,proto3,oneof"`
}

func (*EnvelopeContent_InformeeMessage) isEnvelopeContent_SomeEnvelopeContent() {}

func (*EnvelopeContent_EncryptedViewMessage) isEnvelopeContent_SomeEnvelopeContent() {}

func (*EnvelopeContent_UnassignmentMediatorMessage) isEnvelopeContent_SomeEnvelopeContent() {}

func (*EnvelopeContent_AssignmentMediatorMessage) isEnvelopeContent_SomeEnvelopeContent() {}

func (*EnvelopeContent_RootHashMessage) isEnvelopeContent_SomeEnvelopeContent() {}

func (*EnvelopeContent_TopologyTransactionsBroadcast) isEnvelopeContent_SomeEnvelopeContent() {}

var File_com_digitalasset_canton_protocol_v30_synchronization_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDesc = "" +
	"\n" +
	":com/digitalasset/canton/protocol/v30/synchronization.proto\x12$com.digitalasset.canton.protocol.v30\x1a/com/digitalasset/canton/crypto/v30/crypto.proto\x1aCcom/digitalasset/canton/protocol/v30/participant_reassignment.proto\x1aBcom/digitalasset/canton/protocol/v30/participant_transaction.proto\x1a3com/digitalasset/canton/protocol/v30/topology.proto\"\x8e\x02\n" +
	"!TypedSignedProtocolMessageContent\x127\n" +
	"\x16confirmation_responses\x18\x02 \x01(\fH\x00R\x15confirmationResponses\x121\n" +
	"\x13confirmation_result\x18\x03 \x01(\fH\x00R\x12confirmationResult\x12'\n" +
	"\x0eacs_commitment\x18\x04 \x01(\fH\x00R\racsCommitment\x124\n" +
	"\x15set_traffic_purchased\x18\x05 \x01(\fH\x00R\x13setTrafficPurchasedB\x1e\n" +
	"\x1csome_signed_protocol_message\"\xb6\x01\n" +
	"\x15SignedProtocolMessage\x12K\n" +
	"\tsignature\x18\x01 \x03(\v2-.com.digitalasset.canton.crypto.v30.SignatureR\tsignature\x12P\n" +
	"%typed_signed_protocol_message_content\x18\x02 \x01(\fR!typedSignedProtocolMessageContent\"\x85\x06\n" +
	"\x0fEnvelopeContent\x12b\n" +
	"\x10informee_message\x18\x01 \x01(\v25.com.digitalasset.canton.protocol.v30.InformeeMessageH\x00R\x0finformeeMessage\x12r\n" +
	"\x16encrypted_view_message\x18\x02 \x01(\v2:.com.digitalasset.canton.protocol.v30.EncryptedViewMessageH\x00R\x14encryptedViewMessage\x12\x87\x01\n" +
	"\x1dunassignment_mediator_message\x18\x03 \x01(\v2A.com.digitalasset.canton.protocol.v30.UnassignmentMediatorMessageH\x00R\x1bunassignmentMediatorMessage\x12\x81\x01\n" +
	"\x1bassignment_mediator_message\x18\x04 \x01(\v2?.com.digitalasset.canton.protocol.v30.AssignmentMediatorMessageH\x00R\x19assignmentMediatorMessage\x12c\n" +
	"\x11root_hash_message\x18\x05 \x01(\v25.com.digitalasset.canton.protocol.v30.RootHashMessageH\x00R\x0frootHashMessage\x12\x8d\x01\n" +
	"\x1ftopology_transactions_broadcast\x18\x06 \x01(\v2C.com.digitalasset.canton.protocol.v30.TopologyTransactionsBroadcastH\x00R\x1dtopologyTransactionsBroadcastB\x17\n" +
	"\x15some_envelope_contentBUZSgithub.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/protocol/v30b\x06proto3"

var (
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescData []byte
)

func file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDescData
}

var file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_com_digitalasset_canton_protocol_v30_synchronization_proto_goTypes = []any{
	(*TypedSignedProtocolMessageContent)(nil), // 0: com.digitalasset.canton.protocol.v30.TypedSignedProtocolMessageContent
	(*SignedProtocolMessage)(nil),             // 1: com.digitalasset.canton.protocol.v30.SignedProtocolMessage
	(*EnvelopeContent)(nil),                   // 2: com.digitalasset.canton.protocol.v30.EnvelopeContent
	(*v30.Signature)(nil),                     // 3: com.digitalasset.canton.crypto.v30.Signature
	(*InformeeMessage)(nil),                   // 4: com.digitalasset.canton.protocol.v30.InformeeMessage
	(*EncryptedViewMessage)(nil),              // 5: com.digitalasset.canton.protocol.v30.EncryptedViewMessage
	(*UnassignmentMediatorMessage)(nil),       // 6: com.digitalasset.canton.protocol.v30.UnassignmentMediatorMessage
	(*AssignmentMediatorMessage)(nil),         // 7: com.digitalasset.canton.protocol.v30.AssignmentMediatorMessage
	(*RootHashMessage)(nil),                   // 8: com.digitalasset.canton.protocol.v30.RootHashMessage
	(*TopologyTransactionsBroadcast)(nil),     // 9: com.digitalasset.canton.protocol.v30.TopologyTransactionsBroadcast
}
var file_com_digitalasset_canton_protocol_v30_synchronization_proto_depIdxs = []int32{
	3, // 0: com.digitalasset.canton.protocol.v30.SignedProtocolMessage.signature:type_name -> com.digitalasset.canton.crypto.v30.Signature
	4, // 1: com.digitalasset.canton.protocol.v30.EnvelopeContent.informee_message:type_name -> com.digitalasset.canton.protocol.v30.InformeeMessage
	5, // 2: com.digitalasset.canton.protocol.v30.EnvelopeContent.encrypted_view_message:type_name -> com.digitalasset.canton.protocol.v30.EncryptedViewMessage
	6, // 3: com.digitalasset.canton.protocol.v30.EnvelopeContent.unassignment_mediator_message:type_name -> com.digitalasset.canton.protocol.v30.UnassignmentMediatorMessage
	7, // 4: com.digitalasset.canton.protocol.v30.EnvelopeContent.assignment_mediator_message:type_name -> com.digitalasset.canton.protocol.v30.AssignmentMediatorMessage
	8, // 5: com.digitalasset.canton.protocol.v30.EnvelopeContent.root_hash_message:type_name -> com.digitalasset.canton.protocol.v30.RootHashMessage
	9, // 6: com.digitalasset.canton.protocol.v30.EnvelopeContent.topology_transactions_broadcast:type_name -> com.digitalasset.canton.protocol.v30.TopologyTransactionsBroadcast
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_protocol_v30_synchronization_proto_init() }
func file_com_digitalasset_canton_protocol_v30_synchronization_proto_init() {
	if File_com_digitalasset_canton_protocol_v30_synchronization_proto != nil {
		return
	}
	file_com_digitalasset_canton_protocol_v30_participant_reassignment_proto_init()
	file_com_digitalasset_canton_protocol_v30_participant_transaction_proto_init()
	file_com_digitalasset_canton_protocol_v30_topology_proto_init()
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[0].OneofWrappers = []any{
		(*TypedSignedProtocolMessageContent_ConfirmationResponses)(nil),
		(*TypedSignedProtocolMessageContent_ConfirmationResult)(nil),
		(*TypedSignedProtocolMessageContent_AcsCommitment)(nil),
		(*TypedSignedProtocolMessageContent_SetTrafficPurchased)(nil),
	}
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes[2].OneofWrappers = []any{
		(*EnvelopeContent_InformeeMessage)(nil),
		(*EnvelopeContent_EncryptedViewMessage)(nil),
		(*EnvelopeContent_UnassignmentMediatorMessage)(nil),
		(*EnvelopeContent_AssignmentMediatorMessage)(nil),
		(*EnvelopeContent_RootHashMessage)(nil),
		(*EnvelopeContent_TopologyTransactionsBroadcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v30_synchronization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_digitalasset_canton_protocol_v30_synchronization_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_protocol_v30_synchronization_proto_depIdxs,
		MessageInfos:      file_com_digitalasset_canton_protocol_v30_synchronization_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_protocol_v30_synchronization_proto = out.File
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_goTypes = nil
	file_com_digitalasset_canton_protocol_v30_synchronization_proto_depIdxs = nil
}
