# Copyright (c) 2017-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "dazl"
version = "8.9.0"
description = "high-level Ledger API client for Daml ledgers"
license = "Apache-2.0"
authors = [
    { name = "Davin K. Tanabe", email = "davin.tanabe@digitalasset.com" },
]
readme = 'README.md'
repository = "https://github.com/digital-asset/dazl-client"
homepage = "https://github.com/digital-asset/dazl-client"
keywords = ["daml", "blockchain", "dlt", "distributed ledger", "digital asset"]
requires-python = "<4.0,>=3.10"
dependencies = [
    "attrs>=22.2.0",
    "googleapis_common_protos",
    "grpcio>=1.72.0",
    "httpx>=0.27.0",
    "protobuf>=6",
    "python-dateutil>=2.8.1",
    "semver",
    "typing_extensions",
]

[tool.poetry]
packages = [
    { include = "dazl", from = "python" },
    { include = "_dazl", from = "python" },
]

[project.optional-dependencies]
tls-testing = [
    "cryptography",
]
pygments = [
    "pygments",
]

[tool.poetry.scripts]
dazl = 'dazl.cli:main'

[dependency-groups]
dev = [
    "grpc-stubs",
    "grpcio-tools>=1.72.0",
    "mypy",
    "openapi-python-client",
    "pyjwt",
    "pytest",
    "pytest-asyncio",
    "pyyaml",
    "rich",
    "sphinx",
    "sphinx-autobuild",
    "sphinx-markdown-builder",
    "tomli (>=2.0.1,<3.0) ; python_version < '3.11'",
    "types-protobuf",
    "types-pyyaml",
    "types-requests",
    "watchdog",
]

[tool.ruff]
line-length = 100
lint.isort.required-imports = ["from __future__ import annotations"]
lint.isort.combine-as-imports = true
lint.isort.force-sort-within-sections = true

[tool.mypy]
cache_dir = '.cache/mypy'
#disallow_untyped_defs = true
namespace_packages = true

[[tool.mypy.overrides]]
module = ['google._upb.*', 'google.protobuf.pyext.*', 'google.rpc.*', 'google.rpc.status_pb2.*', 'grpc._cython.*', 'grpc.aio.*', 'grpc_tools.*', 'psutil.*', 'pygments.*', 'semver.*']
ignore_missing_imports = true

[tool.pytest.ini_options]
cache_dir = ".cache/pytest"
log_cli = true
log_cli_level = "DEBUG"
junit_family = "xunit1"
testpaths = ["python/tests/structure", "python/tests/unit"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
