// Copyright (c) 2017-2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: com/digitalasset/canton/participant/admin/v0/party_name_management.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PartyNameManagementServiceClient is the client API for PartyNameManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartyNameManagementServiceClient interface {
	SetPartyDisplayName(ctx context.Context, in *SetPartyDisplayNameRequest, opts ...grpc.CallOption) (*SetPartyDisplayNameResponse, error)
}

type partyNameManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartyNameManagementServiceClient(cc grpc.ClientConnInterface) PartyNameManagementServiceClient {
	return &partyNameManagementServiceClient{cc}
}

func (c *partyNameManagementServiceClient) SetPartyDisplayName(ctx context.Context, in *SetPartyDisplayNameRequest, opts ...grpc.CallOption) (*SetPartyDisplayNameResponse, error) {
	out := new(SetPartyDisplayNameResponse)
	err := c.cc.Invoke(ctx, "/com.digitalasset.canton.participant.admin.v0.PartyNameManagementService/setPartyDisplayName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyNameManagementServiceServer is the server API for PartyNameManagementService service.
// All implementations must embed UnimplementedPartyNameManagementServiceServer
// for forward compatibility
type PartyNameManagementServiceServer interface {
	SetPartyDisplayName(context.Context, *SetPartyDisplayNameRequest) (*SetPartyDisplayNameResponse, error)
	mustEmbedUnimplementedPartyNameManagementServiceServer()
}

// UnimplementedPartyNameManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPartyNameManagementServiceServer struct {
}

func (UnimplementedPartyNameManagementServiceServer) SetPartyDisplayName(context.Context, *SetPartyDisplayNameRequest) (*SetPartyDisplayNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPartyDisplayName not implemented")
}
func (UnimplementedPartyNameManagementServiceServer) mustEmbedUnimplementedPartyNameManagementServiceServer() {
}

// UnsafePartyNameManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartyNameManagementServiceServer will
// result in compilation errors.
type UnsafePartyNameManagementServiceServer interface {
	mustEmbedUnimplementedPartyNameManagementServiceServer()
}

func RegisterPartyNameManagementServiceServer(s grpc.ServiceRegistrar, srv PartyNameManagementServiceServer) {
	s.RegisterService(&PartyNameManagementService_ServiceDesc, srv)
}

func _PartyNameManagementService_SetPartyDisplayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPartyDisplayNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyNameManagementServiceServer).SetPartyDisplayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.digitalasset.canton.participant.admin.v0.PartyNameManagementService/setPartyDisplayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyNameManagementServiceServer).SetPartyDisplayName(ctx, req.(*SetPartyDisplayNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartyNameManagementService_ServiceDesc is the grpc.ServiceDesc for PartyNameManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartyNameManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.digitalasset.canton.participant.admin.v0.PartyNameManagementService",
	HandlerType: (*PartyNameManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setPartyDisplayName",
			Handler:    _PartyNameManagementService_SetPartyDisplayName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/digitalasset/canton/participant/admin/v0/party_name_management.proto",
}
