// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: com/digitalasset/canton/version/untyped_versioned_message.proto

package version

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UntypedVersionedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Wrapper:
	//
	//	*UntypedVersionedMessage_Data
	Wrapper       isUntypedVersionedMessage_Wrapper `protobuf_oneof:"wrapper"`
	Version       int32                             `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntypedVersionedMessage) Reset() {
	*x = UntypedVersionedMessage{}
	mi := &file_com_digitalasset_canton_version_untyped_versioned_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntypedVersionedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntypedVersionedMessage) ProtoMessage() {}

func (x *UntypedVersionedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_version_untyped_versioned_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntypedVersionedMessage.ProtoReflect.Descriptor instead.
func (*UntypedVersionedMessage) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescGZIP(), []int{0}
}

func (x *UntypedVersionedMessage) GetWrapper() isUntypedVersionedMessage_Wrapper {
	if x != nil {
		return x.Wrapper
	}
	return nil
}

func (x *UntypedVersionedMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Wrapper.(*UntypedVersionedMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *UntypedVersionedMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type isUntypedVersionedMessage_Wrapper interface {
	isUntypedVersionedMessage_Wrapper()
}

type UntypedVersionedMessage_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

func (*UntypedVersionedMessage_Data) isUntypedVersionedMessage_Wrapper() {}

var File_com_digitalasset_canton_version_untyped_versioned_message_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDesc = "" +
	"\n" +
	"?com/digitalasset/canton/version/untyped_versioned_message.proto\x12\x1fcom.digitalasset.canton.version\"T\n" +
	"\x17UntypedVersionedMessage\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversionB\t\n" +
	"\awrapperBPZNgithub.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/versionb\x06proto3"

var (
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescData []byte
)

func file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDesc), len(file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDescData
}

var file_com_digitalasset_canton_version_untyped_versioned_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_digitalasset_canton_version_untyped_versioned_message_proto_goTypes = []any{
	(*UntypedVersionedMessage)(nil), // 0: com.digitalasset.canton.version.UntypedVersionedMessage
}
var file_com_digitalasset_canton_version_untyped_versioned_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_version_untyped_versioned_message_proto_init() }
func file_com_digitalasset_canton_version_untyped_versioned_message_proto_init() {
	if File_com_digitalasset_canton_version_untyped_versioned_message_proto != nil {
		return
	}
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_msgTypes[0].OneofWrappers = []any{
		(*UntypedVersionedMessage_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDesc), len(file_com_digitalasset_canton_version_untyped_versioned_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_digitalasset_canton_version_untyped_versioned_message_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_version_untyped_versioned_message_proto_depIdxs,
		MessageInfos:      file_com_digitalasset_canton_version_untyped_versioned_message_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_version_untyped_versioned_message_proto = out.File
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_goTypes = nil
	file_com_digitalasset_canton_version_untyped_versioned_message_proto_depIdxs = nil
}
