# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:18.04

COPY setup.sh /setup.sh

CMD "/setup.sh"
