#!/usr/bin/env bash
# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
set -euox pipefail

url=https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
sha256=3784cfc4670f0d4c5482604c7c513beb1a92b005f569df9bf100e8bef6610f2e

function install {
    if ! link ; then
        (
            set -euox pipefail

            mkdir -p "${HOME}/.java"
            cd "${HOME}/.java"
            curl -sSL "${url}" -o "jdk-11.tar.gz"
            actual="$(sha256sum "jdk-11.tar.gz" | cut -f 1 -d' ')"
            if [ "${actual}" != "${sha256}" ]; then
                echo "Failed verification!"
                echo "    URL:             ${url}"
                echo "    Expected SHA256: ${sha256}"
                echo "    Actual SHA256:   ${actual}"
                exit 1
            fi
            tar xfz "jdk-11.tar.gz"
            rm "jdk-11.tar.gz"
        )

        link
    fi
}

function link {
    mkdir -p "$HOME/bin"
    [ -f "${HOME}/.java/jdk-11/bin/java" ] && \
        ln -s "${HOME}/.java/jdk-11/bin/java" "$HOME/bin/"
}

install
