// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: com/digitalasset/canton/synchronizer/sequencing/sequencer/bftordering/standalone/v1/standalone_bft_ordering_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RejectionReason *string                `protobuf:"bytes,1,opt,name=rejection_reason,json=rejectionReason,proto3,oneof" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetRejectionReason() string {
	if x != nil && x.RejectionReason != nil {
		return *x.RejectionReason
	}
	return ""
}

type ReadOrderedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   int64                  `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOrderedRequest) Reset() {
	*x = ReadOrderedRequest{}
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOrderedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOrderedRequest) ProtoMessage() {}

func (x *ReadOrderedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOrderedRequest.ProtoReflect.Descriptor instead.
func (*ReadOrderedRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOrderedRequest) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

type ReadOrderedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Block         []*Ordered             `protobuf:"bytes,2,rep,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOrderedResponse) Reset() {
	*x = ReadOrderedResponse{}
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOrderedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOrderedResponse) ProtoMessage() {}

func (x *ReadOrderedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOrderedResponse.ProtoReflect.Descriptor instead.
func (*ReadOrderedResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadOrderedResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ReadOrderedResponse) GetBlock() []*Ordered {
	if x != nil {
		return x.Block
	}
	return nil
}

type Ordered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ordered) Reset() {
	*x = Ordered{}
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ordered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ordered) ProtoMessage() {}

func (x *Ordered) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ordered.ProtoReflect.Descriptor instead.
func (*Ordered) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP(), []int{4}
}

func (x *Ordered) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Ordered) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDesc = "" +
	"\n" +
	"ycom/digitalasset/canton/synchronizer/sequencing/sequencer/bftordering/standalone/v1/standalone_bft_ordering_service.proto\x12Scom.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1\"9\n" +
	"\vSendRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"S\n" +
	"\fSendResponse\x12.\n" +
	"\x10rejection_reason\x18\x01 \x01(\tH\x00R\x0frejectionReason\x88\x01\x01B\x13\n" +
	"\x11_rejection_reason\"7\n" +
	"\x12ReadOrderedRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x03R\vstartHeight\"\xa1\x01\n" +
	"\x13ReadOrderedResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12r\n" +
	"\x05block\x18\x02 \x03(\v2\\.com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.OrderedR\x05block\"5\n" +
	"\aOrdered\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2\xd1\x03\n" +
	"\x1cStandaloneBftOrderingService\x12\xcb\x01\n" +
	"\x04Send\x12`.com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendRequest\x1aa.com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendResponse\x12\xe2\x01\n" +
	"\vReadOrdered\x12g.com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedRequest\x1ah.com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedResponse0\x01B\x85\x01Z\x82\x01github.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/synchronizer/sequencing/sequencer/bftordering/standalone/v1b\x06proto3"

var (
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescData []byte
)

func file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDesc), len(file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDescData
}

var file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_goTypes = []any{
	(*SendRequest)(nil),         // 0: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendRequest
	(*SendResponse)(nil),        // 1: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendResponse
	(*ReadOrderedRequest)(nil),  // 2: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedRequest
	(*ReadOrderedResponse)(nil), // 3: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedResponse
	(*Ordered)(nil),             // 4: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.Ordered
}
var file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_depIdxs = []int32{
	4, // 0: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedResponse.block:type_name -> com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.Ordered
	0, // 1: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.StandaloneBftOrderingService.Send:input_type -> com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendRequest
	2, // 2: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.StandaloneBftOrderingService.ReadOrdered:input_type -> com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedRequest
	1, // 3: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.StandaloneBftOrderingService.Send:output_type -> com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.SendResponse
	3, // 4: com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.StandaloneBftOrderingService.ReadOrdered:output_type -> com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.standalone.v1.ReadOrderedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_init()
}
func file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_init() {
	if File_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto != nil {
		return
	}
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDesc), len(file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_depIdxs,
		MessageInfos:      file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto = out.File
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_goTypes = nil
	file_com_digitalasset_canton_synchronizer_sequencing_sequencer_bftordering_standalone_v1_standalone_bft_ordering_service_proto_depIdxs = nil
}
