// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: com/digitalasset/canton/mediator/admin/v30/mediator_inspection_service.proto

package v30

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerdictResult int32

const (
	VerdictResult_VERDICT_RESULT_UNSPECIFIED VerdictResult = 0
	VerdictResult_VERDICT_RESULT_ACCEPTED    VerdictResult = 1
	VerdictResult_VERDICT_RESULT_REJECTED    VerdictResult = 2
)

// Enum value maps for VerdictResult.
var (
	VerdictResult_name = map[int32]string{
		0: "VERDICT_RESULT_UNSPECIFIED",
		1: "VERDICT_RESULT_ACCEPTED",
		2: "VERDICT_RESULT_REJECTED",
	}
	VerdictResult_value = map[string]int32{
		"VERDICT_RESULT_UNSPECIFIED": 0,
		"VERDICT_RESULT_ACCEPTED":    1,
		"VERDICT_RESULT_REJECTED":    2,
	}
)

func (x VerdictResult) Enum() *VerdictResult {
	p := new(VerdictResult)
	*p = x
	return p
}

func (x VerdictResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerdictResult) Descriptor() protoreflect.EnumDescriptor {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_enumTypes[0].Descriptor()
}

func (VerdictResult) Type() protoreflect.EnumType {
	return &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_enumTypes[0]
}

func (x VerdictResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerdictResult.Descriptor instead.
func (VerdictResult) EnumDescriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{0}
}

type VerdictsRequest struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	MostRecentlyReceivedRecordTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=most_recently_received_record_time,json=mostRecentlyReceivedRecordTime,proto3,oneof" json:"most_recently_received_record_time,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *VerdictsRequest) Reset() {
	*x = VerdictsRequest{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictsRequest) ProtoMessage() {}

func (x *VerdictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictsRequest.ProtoReflect.Descriptor instead.
func (*VerdictsRequest) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{0}
}

func (x *VerdictsRequest) GetMostRecentlyReceivedRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MostRecentlyReceivedRecordTime
	}
	return nil
}

type VerdictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       *Verdict               `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerdictsResponse) Reset() {
	*x = VerdictsResponse{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerdictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerdictsResponse) ProtoMessage() {}

func (x *VerdictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerdictsResponse.ProtoReflect.Descriptor instead.
func (*VerdictsResponse) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{1}
}

func (x *VerdictsResponse) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type Verdict struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SubmittingParties        []string               `protobuf:"bytes,1,rep,name=submitting_parties,json=submittingParties,proto3" json:"submitting_parties,omitempty"`
	SubmittingParticipantUid string                 `protobuf:"bytes,2,opt,name=submitting_participant_uid,json=submittingParticipantUid,proto3" json:"submitting_participant_uid,omitempty"`
	Verdict                  VerdictResult          `protobuf:"varint,3,opt,name=verdict,proto3,enum=com.digitalasset.canton.mediator.admin.v30.VerdictResult" json:"verdict,omitempty"`
	FinalizationTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finalization_time,json=finalizationTime,proto3" json:"finalization_time,omitempty"`
	RecordTime               *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=record_time,json=recordTime,proto3" json:"record_time,omitempty"`
	MediatorGroup            uint32                 `protobuf:"varint,6,opt,name=mediator_group,json=mediatorGroup,proto3" json:"mediator_group,omitempty"`
	// Types that are valid to be assigned to Views:
	//
	//	*Verdict_TransactionViews
	Views         isVerdict_Views `protobuf_oneof:"views"`
	UpdateId      string          `protobuf:"bytes,8,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{2}
}

func (x *Verdict) GetSubmittingParties() []string {
	if x != nil {
		return x.SubmittingParties
	}
	return nil
}

func (x *Verdict) GetSubmittingParticipantUid() string {
	if x != nil {
		return x.SubmittingParticipantUid
	}
	return ""
}

func (x *Verdict) GetVerdict() VerdictResult {
	if x != nil {
		return x.Verdict
	}
	return VerdictResult_VERDICT_RESULT_UNSPECIFIED
}

func (x *Verdict) GetFinalizationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinalizationTime
	}
	return nil
}

func (x *Verdict) GetRecordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordTime
	}
	return nil
}

func (x *Verdict) GetMediatorGroup() uint32 {
	if x != nil {
		return x.MediatorGroup
	}
	return 0
}

func (x *Verdict) GetViews() isVerdict_Views {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *Verdict) GetTransactionViews() *TransactionViews {
	if x != nil {
		if x, ok := x.Views.(*Verdict_TransactionViews); ok {
			return x.TransactionViews
		}
	}
	return nil
}

func (x *Verdict) GetUpdateId() string {
	if x != nil {
		return x.UpdateId
	}
	return ""
}

type isVerdict_Views interface {
	isVerdict_Views()
}

type Verdict_TransactionViews struct {
	TransactionViews *TransactionViews `protobuf:"bytes,7,opt,name=transaction_views,json=transactionViews,proto3,oneof"`
}

func (*Verdict_TransactionViews) isVerdict_Views() {}

type TransactionViews struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Views         map[int32]*TransactionView `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RootViews     []int32                    `protobuf:"varint,2,rep,packed,name=root_views,json=rootViews,proto3" json:"root_views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionViews) Reset() {
	*x = TransactionViews{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionViews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionViews) ProtoMessage() {}

func (x *TransactionViews) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionViews.ProtoReflect.Descriptor instead.
func (*TransactionViews) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionViews) GetViews() map[int32]*TransactionView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *TransactionViews) GetRootViews() []int32 {
	if x != nil {
		return x.RootViews
	}
	return nil
}

type TransactionView struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Informees         []string               `protobuf:"bytes,1,rep,name=informees,proto3" json:"informees,omitempty"`
	ConfirmingParties []*Quorum              `protobuf:"bytes,2,rep,name=confirming_parties,json=confirmingParties,proto3" json:"confirming_parties,omitempty"`
	SubViews          []int32                `protobuf:"varint,3,rep,packed,name=sub_views,json=subViews,proto3" json:"sub_views,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionView) Reset() {
	*x = TransactionView{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionView) ProtoMessage() {}

func (x *TransactionView) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionView.ProtoReflect.Descriptor instead.
func (*TransactionView) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionView) GetInformees() []string {
	if x != nil {
		return x.Informees
	}
	return nil
}

func (x *TransactionView) GetConfirmingParties() []*Quorum {
	if x != nil {
		return x.ConfirmingParties
	}
	return nil
}

func (x *TransactionView) GetSubViews() []int32 {
	if x != nil {
		return x.SubViews
	}
	return nil
}

type Quorum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parties       []string               `protobuf:"bytes,1,rep,name=parties,proto3" json:"parties,omitempty"`
	Threshold     int32                  `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quorum) Reset() {
	*x = Quorum{}
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quorum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quorum) ProtoMessage() {}

func (x *Quorum) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quorum.ProtoReflect.Descriptor instead.
func (*Quorum) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP(), []int{5}
}

func (x *Quorum) GetParties() []string {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *Quorum) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

var File_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDesc = "" +
	"\n" +
	"Lcom/digitalasset/canton/mediator/admin/v30/mediator_inspection_service.proto\x12*com.digitalasset.canton.mediator.admin.v30\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\x0fVerdictsRequest\x12k\n" +
	"\"most_recently_received_record_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x1emostRecentlyReceivedRecordTime\x88\x01\x01B%\n" +
	"#_most_recently_received_record_time\"a\n" +
	"\x10VerdictsResponse\x12M\n" +
	"\averdict\x18\x01 \x01(\v23.com.digitalasset.canton.mediator.admin.v30.VerdictR\averdict\"\x8b\x04\n" +
	"\aVerdict\x12-\n" +
	"\x12submitting_parties\x18\x01 \x03(\tR\x11submittingParties\x12<\n" +
	"\x1asubmitting_participant_uid\x18\x02 \x01(\tR\x18submittingParticipantUid\x12S\n" +
	"\averdict\x18\x03 \x01(\x0e29.com.digitalasset.canton.mediator.admin.v30.VerdictResultR\averdict\x12G\n" +
	"\x11finalization_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10finalizationTime\x12;\n" +
	"\vrecord_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordTime\x12%\n" +
	"\x0emediator_group\x18\x06 \x01(\rR\rmediatorGroup\x12k\n" +
	"\x11transaction_views\x18\a \x01(\v2<.com.digitalasset.canton.mediator.admin.v30.TransactionViewsH\x00R\x10transactionViews\x12\x1b\n" +
	"\tupdate_id\x18\b \x01(\tR\bupdateIdB\a\n" +
	"\x05views\"\x87\x02\n" +
	"\x10TransactionViews\x12]\n" +
	"\x05views\x18\x01 \x03(\v2G.com.digitalasset.canton.mediator.admin.v30.TransactionViews.ViewsEntryR\x05views\x12\x1d\n" +
	"\n" +
	"root_views\x18\x02 \x03(\x05R\trootViews\x1au\n" +
	"\n" +
	"ViewsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12Q\n" +
	"\x05value\x18\x02 \x01(\v2;.com.digitalasset.canton.mediator.admin.v30.TransactionViewR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0fTransactionView\x12\x1c\n" +
	"\tinformees\x18\x01 \x03(\tR\tinformees\x12a\n" +
	"\x12confirming_parties\x18\x02 \x03(\v22.com.digitalasset.canton.mediator.admin.v30.QuorumR\x11confirmingParties\x12\x1b\n" +
	"\tsub_views\x18\x03 \x03(\x05R\bsubViews\"@\n" +
	"\x06Quorum\x12\x18\n" +
	"\aparties\x18\x01 \x03(\tR\aparties\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x05R\tthreshold*i\n" +
	"\rVerdictResult\x12\x1e\n" +
	"\x1aVERDICT_RESULT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VERDICT_RESULT_ACCEPTED\x10\x01\x12\x1b\n" +
	"\x17VERDICT_RESULT_REJECTED\x10\x022\xa5\x01\n" +
	"\x19MediatorInspectionService\x12\x87\x01\n" +
	"\bVerdicts\x12;.com.digitalasset.canton.mediator.admin.v30.VerdictsRequest\x1a<.com.digitalasset.canton.mediator.admin.v30.VerdictsResponse0\x01B[ZYgithub.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/mediator/admin/v30b\x06proto3"

var (
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescData []byte
)

func file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDesc), len(file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDescData
}

var file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_goTypes = []any{
	(VerdictResult)(0),            // 0: com.digitalasset.canton.mediator.admin.v30.VerdictResult
	(*VerdictsRequest)(nil),       // 1: com.digitalasset.canton.mediator.admin.v30.VerdictsRequest
	(*VerdictsResponse)(nil),      // 2: com.digitalasset.canton.mediator.admin.v30.VerdictsResponse
	(*Verdict)(nil),               // 3: com.digitalasset.canton.mediator.admin.v30.Verdict
	(*TransactionViews)(nil),      // 4: com.digitalasset.canton.mediator.admin.v30.TransactionViews
	(*TransactionView)(nil),       // 5: com.digitalasset.canton.mediator.admin.v30.TransactionView
	(*Quorum)(nil),                // 6: com.digitalasset.canton.mediator.admin.v30.Quorum
	nil,                           // 7: com.digitalasset.canton.mediator.admin.v30.TransactionViews.ViewsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_depIdxs = []int32{
	8,  // 0: com.digitalasset.canton.mediator.admin.v30.VerdictsRequest.most_recently_received_record_time:type_name -> google.protobuf.Timestamp
	3,  // 1: com.digitalasset.canton.mediator.admin.v30.VerdictsResponse.verdict:type_name -> com.digitalasset.canton.mediator.admin.v30.Verdict
	0,  // 2: com.digitalasset.canton.mediator.admin.v30.Verdict.verdict:type_name -> com.digitalasset.canton.mediator.admin.v30.VerdictResult
	8,  // 3: com.digitalasset.canton.mediator.admin.v30.Verdict.finalization_time:type_name -> google.protobuf.Timestamp
	8,  // 4: com.digitalasset.canton.mediator.admin.v30.Verdict.record_time:type_name -> google.protobuf.Timestamp
	4,  // 5: com.digitalasset.canton.mediator.admin.v30.Verdict.transaction_views:type_name -> com.digitalasset.canton.mediator.admin.v30.TransactionViews
	7,  // 6: com.digitalasset.canton.mediator.admin.v30.TransactionViews.views:type_name -> com.digitalasset.canton.mediator.admin.v30.TransactionViews.ViewsEntry
	6,  // 7: com.digitalasset.canton.mediator.admin.v30.TransactionView.confirming_parties:type_name -> com.digitalasset.canton.mediator.admin.v30.Quorum
	5,  // 8: com.digitalasset.canton.mediator.admin.v30.TransactionViews.ViewsEntry.value:type_name -> com.digitalasset.canton.mediator.admin.v30.TransactionView
	1,  // 9: com.digitalasset.canton.mediator.admin.v30.MediatorInspectionService.Verdicts:input_type -> com.digitalasset.canton.mediator.admin.v30.VerdictsRequest
	2,  // 10: com.digitalasset.canton.mediator.admin.v30.MediatorInspectionService.Verdicts:output_type -> com.digitalasset.canton.mediator.admin.v30.VerdictsResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_init() }
func file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_init() {
	if File_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto != nil {
		return
	}
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes[2].OneofWrappers = []any{
		(*Verdict_TransactionViews)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDesc), len(file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_depIdxs,
		EnumInfos:         file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_enumTypes,
		MessageInfos:      file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto = out.File
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_goTypes = nil
	file_com_digitalasset_canton_mediator_admin_v30_mediator_inspection_service_proto_depIdxs = nil
}
