// Copyright (c) 2017-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: com/digitalasset/canton/admin/participant/v30/participant_replication_service.proto

package v30

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParticipantReplicationService_SetPassive_FullMethodName = "/com.digitalasset.canton.admin.participant.v30.ParticipantReplicationService/SetPassive"
)

// ParticipantReplicationServiceClient is the client API for ParticipantReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParticipantReplicationServiceClient interface {
	SetPassive(ctx context.Context, in *SetPassiveRequest, opts ...grpc.CallOption) (*SetPassiveResponse, error)
}

type participantReplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParticipantReplicationServiceClient(cc grpc.ClientConnInterface) ParticipantReplicationServiceClient {
	return &participantReplicationServiceClient{cc}
}

func (c *participantReplicationServiceClient) SetPassive(ctx context.Context, in *SetPassiveRequest, opts ...grpc.CallOption) (*SetPassiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPassiveResponse)
	err := c.cc.Invoke(ctx, ParticipantReplicationService_SetPassive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParticipantReplicationServiceServer is the server API for ParticipantReplicationService service.
// All implementations must embed UnimplementedParticipantReplicationServiceServer
// for forward compatibility.
type ParticipantReplicationServiceServer interface {
	SetPassive(context.Context, *SetPassiveRequest) (*SetPassiveResponse, error)
	mustEmbedUnimplementedParticipantReplicationServiceServer()
}

// UnimplementedParticipantReplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParticipantReplicationServiceServer struct{}

func (UnimplementedParticipantReplicationServiceServer) SetPassive(context.Context, *SetPassiveRequest) (*SetPassiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassive not implemented")
}
func (UnimplementedParticipantReplicationServiceServer) mustEmbedUnimplementedParticipantReplicationServiceServer() {
}
func (UnimplementedParticipantReplicationServiceServer) testEmbeddedByValue() {}

// UnsafeParticipantReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParticipantReplicationServiceServer will
// result in compilation errors.
type UnsafeParticipantReplicationServiceServer interface {
	mustEmbedUnimplementedParticipantReplicationServiceServer()
}

func RegisterParticipantReplicationServiceServer(s grpc.ServiceRegistrar, srv ParticipantReplicationServiceServer) {
	// If the following call pancis, it indicates UnimplementedParticipantReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParticipantReplicationService_ServiceDesc, srv)
}

func _ParticipantReplicationService_SetPassive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPassiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParticipantReplicationServiceServer).SetPassive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParticipantReplicationService_SetPassive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParticipantReplicationServiceServer).SetPassive(ctx, req.(*SetPassiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParticipantReplicationService_ServiceDesc is the grpc.ServiceDesc for ParticipantReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParticipantReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.digitalasset.canton.admin.participant.v30.ParticipantReplicationService",
	HandlerType: (*ParticipantReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPassive",
			Handler:    _ParticipantReplicationService_SetPassive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/digitalasset/canton/admin/participant/v30/participant_replication_service.proto",
}
