// Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: com/digitalasset/canton/protocol/v1/mediator.proto

package v1

import (
	v0 "github.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/protocol/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionResultMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Verdict          *Verdict               `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	NotificationTree *InformeeTree          `protobuf:"bytes,5,opt,name=notification_tree,json=notificationTree,proto3" json:"notification_tree,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionResultMessage) Reset() {
	*x = TransactionResultMessage{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResultMessage) ProtoMessage() {}

func (x *TransactionResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResultMessage.ProtoReflect.Descriptor instead.
func (*TransactionResultMessage) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionResultMessage) GetRequestId() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *TransactionResultMessage) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *TransactionResultMessage) GetNotificationTree() *InformeeTree {
	if x != nil {
		return x.NotificationTree
	}
	return nil
}

type Verdict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SomeVerdict:
	//
	//	*Verdict_Approve
	//	*Verdict_ParticipantReject
	//	*Verdict_MediatorReject
	SomeVerdict   isVerdict_SomeVerdict `protobuf_oneof:"some_verdict"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{1}
}

func (x *Verdict) GetSomeVerdict() isVerdict_SomeVerdict {
	if x != nil {
		return x.SomeVerdict
	}
	return nil
}

func (x *Verdict) GetApprove() *emptypb.Empty {
	if x != nil {
		if x, ok := x.SomeVerdict.(*Verdict_Approve); ok {
			return x.Approve
		}
	}
	return nil
}

func (x *Verdict) GetParticipantReject() *ParticipantReject {
	if x != nil {
		if x, ok := x.SomeVerdict.(*Verdict_ParticipantReject); ok {
			return x.ParticipantReject
		}
	}
	return nil
}

func (x *Verdict) GetMediatorReject() *MediatorReject {
	if x != nil {
		if x, ok := x.SomeVerdict.(*Verdict_MediatorReject); ok {
			return x.MediatorReject
		}
	}
	return nil
}

type isVerdict_SomeVerdict interface {
	isVerdict_SomeVerdict()
}

type Verdict_Approve struct {
	Approve *emptypb.Empty `protobuf:"bytes,1,opt,name=approve,proto3,oneof"`
}

type Verdict_ParticipantReject struct {
	ParticipantReject *ParticipantReject `protobuf:"bytes,2,opt,name=participant_reject,json=participantReject,proto3,oneof"`
}

type Verdict_MediatorReject struct {
	MediatorReject *MediatorReject `protobuf:"bytes,3,opt,name=mediator_reject,json=mediatorReject,proto3,oneof"`
}

func (*Verdict_Approve) isVerdict_SomeVerdict() {}

func (*Verdict_ParticipantReject) isVerdict_SomeVerdict() {}

func (*Verdict_MediatorReject) isVerdict_SomeVerdict() {}

type InformeeTree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *GenTransactionTree    `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformeeTree) Reset() {
	*x = InformeeTree{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformeeTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformeeTree) ProtoMessage() {}

func (x *InformeeTree) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformeeTree.ProtoReflect.Descriptor instead.
func (*InformeeTree) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{2}
}

func (x *InformeeTree) GetTree() *GenTransactionTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

type ParticipantReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reasons       []*v0.RejectionReason  `protobuf:"bytes,1,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantReject) Reset() {
	*x = ParticipantReject{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantReject) ProtoMessage() {}

func (x *ParticipantReject) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantReject.ProtoReflect.Descriptor instead.
func (*ParticipantReject) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{3}
}

func (x *ParticipantReject) GetReasons() []*v0.RejectionReason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

type MediatorReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorCategory uint32                 `protobuf:"varint,4,opt,name=error_category,json=errorCategory,proto3" json:"error_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediatorReject) Reset() {
	*x = MediatorReject{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediatorReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediatorReject) ProtoMessage() {}

func (x *MediatorReject) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediatorReject.ProtoReflect.Descriptor instead.
func (*MediatorReject) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{4}
}

func (x *MediatorReject) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *MediatorReject) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MediatorReject) GetErrorCategory() uint32 {
	if x != nil {
		return x.ErrorCategory
	}
	return 0
}

type MalformedMediatorRequestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DomainId      string                 `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	ViewType      v0.ViewType            `protobuf:"varint,3,opt,name=view_type,json=viewType,proto3,enum=com.digitalasset.canton.protocol.v0.ViewType" json:"view_type,omitempty"`
	Rejection     *MediatorReject        `protobuf:"bytes,4,opt,name=rejection,proto3" json:"rejection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MalformedMediatorRequestResult) Reset() {
	*x = MalformedMediatorRequestResult{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MalformedMediatorRequestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MalformedMediatorRequestResult) ProtoMessage() {}

func (x *MalformedMediatorRequestResult) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MalformedMediatorRequestResult.ProtoReflect.Descriptor instead.
func (*MalformedMediatorRequestResult) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{5}
}

func (x *MalformedMediatorRequestResult) GetRequestId() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *MalformedMediatorRequestResult) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *MalformedMediatorRequestResult) GetViewType() v0.ViewType {
	if x != nil {
		return x.ViewType
	}
	return v0.ViewType(0)
}

func (x *MalformedMediatorRequestResult) GetRejection() *MediatorReject {
	if x != nil {
		return x.Rejection
	}
	return nil
}

type TransferResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Domain:
	//
	//	*TransferResult_OriginDomain
	//	*TransferResult_TargetDomain
	Domain        isTransferResult_Domain `protobuf_oneof:"domain"`
	Informees     []string                `protobuf:"bytes,4,rep,name=informees,proto3" json:"informees,omitempty"`
	Verdict       *Verdict                `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResult) Reset() {
	*x = TransferResult{}
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResult) ProtoMessage() {}

func (x *TransferResult) ProtoReflect() protoreflect.Message {
	mi := &file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResult.ProtoReflect.Descriptor instead.
func (*TransferResult) Descriptor() ([]byte, []int) {
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP(), []int{6}
}

func (x *TransferResult) GetRequestId() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *TransferResult) GetDomain() isTransferResult_Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *TransferResult) GetOriginDomain() string {
	if x != nil {
		if x, ok := x.Domain.(*TransferResult_OriginDomain); ok {
			return x.OriginDomain
		}
	}
	return ""
}

func (x *TransferResult) GetTargetDomain() string {
	if x != nil {
		if x, ok := x.Domain.(*TransferResult_TargetDomain); ok {
			return x.TargetDomain
		}
	}
	return ""
}

func (x *TransferResult) GetInformees() []string {
	if x != nil {
		return x.Informees
	}
	return nil
}

func (x *TransferResult) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

type isTransferResult_Domain interface {
	isTransferResult_Domain()
}

type TransferResult_OriginDomain struct {
	OriginDomain string `protobuf:"bytes,2,opt,name=origin_domain,json=originDomain,proto3,oneof"`
}

type TransferResult_TargetDomain struct {
	TargetDomain string `protobuf:"bytes,3,opt,name=target_domain,json=targetDomain,proto3,oneof"`
}

func (*TransferResult_OriginDomain) isTransferResult_Domain() {}

func (*TransferResult_TargetDomain) isTransferResult_Domain() {}

var File_com_digitalasset_canton_protocol_v1_mediator_proto protoreflect.FileDescriptor

const file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDesc = "" +
	"\n" +
	"2com/digitalasset/canton/protocol/v1/mediator.proto\x12#com.digitalasset.canton.protocol.v1\x1a0com/digitalasset/canton/protocol/v0/common.proto\x1a2com/digitalasset/canton/protocol/v0/mediator.proto\x1a0com/digitalasset/canton/protocol/v1/merkle.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x18TransactionResultMessage\x129\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\trequestId\x12F\n" +
	"\averdict\x18\x02 \x01(\v2,.com.digitalasset.canton.protocol.v1.VerdictR\averdict\x12^\n" +
	"\x11notification_tree\x18\x05 \x01(\v21.com.digitalasset.canton.protocol.v1.InformeeTreeR\x10notificationTree\"\x9c\x02\n" +
	"\aVerdict\x122\n" +
	"\aapprove\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\aapprove\x12g\n" +
	"\x12participant_reject\x18\x02 \x01(\v26.com.digitalasset.canton.protocol.v1.ParticipantRejectH\x00R\x11participantReject\x12^\n" +
	"\x0fmediator_reject\x18\x03 \x01(\v23.com.digitalasset.canton.protocol.v1.MediatorRejectH\x00R\x0emediatorRejectB\x0e\n" +
	"\fsome_verdictJ\x04\b\x04\x10\x05\"[\n" +
	"\fInformeeTree\x12K\n" +
	"\x04tree\x18\x01 \x01(\v27.com.digitalasset.canton.protocol.v1.GenTransactionTreeR\x04tree\"c\n" +
	"\x11ParticipantReject\x12N\n" +
	"\areasons\x18\x01 \x03(\v24.com.digitalasset.canton.protocol.v0.RejectionReasonR\areasons\"r\n" +
	"\x0eMediatorReject\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12%\n" +
	"\x0eerror_category\x18\x04 \x01(\rR\rerrorCategoryJ\x04\b\x01\x10\x02\"\x97\x02\n" +
	"\x1eMalformedMediatorRequestResult\x129\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\trequestId\x12\x1b\n" +
	"\tdomain_id\x18\x02 \x01(\tR\bdomainId\x12J\n" +
	"\tview_type\x18\x03 \x01(\x0e2-.com.digitalasset.canton.protocol.v0.ViewTypeR\bviewType\x12Q\n" +
	"\trejection\x18\x04 \x01(\v23.com.digitalasset.canton.protocol.v1.MediatorRejectR\trejection\"\x89\x02\n" +
	"\x0eTransferResult\x129\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\trequestId\x12%\n" +
	"\rorigin_domain\x18\x02 \x01(\tH\x00R\foriginDomain\x12%\n" +
	"\rtarget_domain\x18\x03 \x01(\tH\x00R\ftargetDomain\x12\x1c\n" +
	"\tinformees\x18\x04 \x03(\tR\tinformees\x12F\n" +
	"\averdict\x18\x05 \x01(\v2,.com.digitalasset.canton.protocol.v1.VerdictR\averdictB\b\n" +
	"\x06domainBTZRgithub.com/digital-asset/dazl-client/v8/go/api/com/digitalasset/canton/protocol/v1b\x06proto3"

var (
	file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescOnce sync.Once
	file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescData []byte
)

func file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescGZIP() []byte {
	file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescOnce.Do(func() {
		file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDesc)))
	})
	return file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDescData
}

var file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_digitalasset_canton_protocol_v1_mediator_proto_goTypes = []any{
	(*TransactionResultMessage)(nil),       // 0: com.digitalasset.canton.protocol.v1.TransactionResultMessage
	(*Verdict)(nil),                        // 1: com.digitalasset.canton.protocol.v1.Verdict
	(*InformeeTree)(nil),                   // 2: com.digitalasset.canton.protocol.v1.InformeeTree
	(*ParticipantReject)(nil),              // 3: com.digitalasset.canton.protocol.v1.ParticipantReject
	(*MediatorReject)(nil),                 // 4: com.digitalasset.canton.protocol.v1.MediatorReject
	(*MalformedMediatorRequestResult)(nil), // 5: com.digitalasset.canton.protocol.v1.MalformedMediatorRequestResult
	(*TransferResult)(nil),                 // 6: com.digitalasset.canton.protocol.v1.TransferResult
	(*timestamppb.Timestamp)(nil),          // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 8: google.protobuf.Empty
	(*GenTransactionTree)(nil),             // 9: com.digitalasset.canton.protocol.v1.GenTransactionTree
	(*v0.RejectionReason)(nil),             // 10: com.digitalasset.canton.protocol.v0.RejectionReason
	(v0.ViewType)(0),                       // 11: com.digitalasset.canton.protocol.v0.ViewType
}
var file_com_digitalasset_canton_protocol_v1_mediator_proto_depIdxs = []int32{
	7,  // 0: com.digitalasset.canton.protocol.v1.TransactionResultMessage.request_id:type_name -> google.protobuf.Timestamp
	1,  // 1: com.digitalasset.canton.protocol.v1.TransactionResultMessage.verdict:type_name -> com.digitalasset.canton.protocol.v1.Verdict
	2,  // 2: com.digitalasset.canton.protocol.v1.TransactionResultMessage.notification_tree:type_name -> com.digitalasset.canton.protocol.v1.InformeeTree
	8,  // 3: com.digitalasset.canton.protocol.v1.Verdict.approve:type_name -> google.protobuf.Empty
	3,  // 4: com.digitalasset.canton.protocol.v1.Verdict.participant_reject:type_name -> com.digitalasset.canton.protocol.v1.ParticipantReject
	4,  // 5: com.digitalasset.canton.protocol.v1.Verdict.mediator_reject:type_name -> com.digitalasset.canton.protocol.v1.MediatorReject
	9,  // 6: com.digitalasset.canton.protocol.v1.InformeeTree.tree:type_name -> com.digitalasset.canton.protocol.v1.GenTransactionTree
	10, // 7: com.digitalasset.canton.protocol.v1.ParticipantReject.reasons:type_name -> com.digitalasset.canton.protocol.v0.RejectionReason
	7,  // 8: com.digitalasset.canton.protocol.v1.MalformedMediatorRequestResult.request_id:type_name -> google.protobuf.Timestamp
	11, // 9: com.digitalasset.canton.protocol.v1.MalformedMediatorRequestResult.view_type:type_name -> com.digitalasset.canton.protocol.v0.ViewType
	4,  // 10: com.digitalasset.canton.protocol.v1.MalformedMediatorRequestResult.rejection:type_name -> com.digitalasset.canton.protocol.v1.MediatorReject
	7,  // 11: com.digitalasset.canton.protocol.v1.TransferResult.request_id:type_name -> google.protobuf.Timestamp
	1,  // 12: com.digitalasset.canton.protocol.v1.TransferResult.verdict:type_name -> com.digitalasset.canton.protocol.v1.Verdict
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_com_digitalasset_canton_protocol_v1_mediator_proto_init() }
func file_com_digitalasset_canton_protocol_v1_mediator_proto_init() {
	if File_com_digitalasset_canton_protocol_v1_mediator_proto != nil {
		return
	}
	file_com_digitalasset_canton_protocol_v1_merkle_proto_init()
	file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[1].OneofWrappers = []any{
		(*Verdict_Approve)(nil),
		(*Verdict_ParticipantReject)(nil),
		(*Verdict_MediatorReject)(nil),
	}
	file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes[6].OneofWrappers = []any{
		(*TransferResult_OriginDomain)(nil),
		(*TransferResult_TargetDomain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDesc), len(file_com_digitalasset_canton_protocol_v1_mediator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_digitalasset_canton_protocol_v1_mediator_proto_goTypes,
		DependencyIndexes: file_com_digitalasset_canton_protocol_v1_mediator_proto_depIdxs,
		MessageInfos:      file_com_digitalasset_canton_protocol_v1_mediator_proto_msgTypes,
	}.Build()
	File_com_digitalasset_canton_protocol_v1_mediator_proto = out.File
	file_com_digitalasset_canton_protocol_v1_mediator_proto_goTypes = nil
	file_com_digitalasset_canton_protocol_v1_mediator_proto_depIdxs = nil
}
