# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# fmt: off

import typing as _typing

from google.protobuf.descriptor import FieldDescriptor as __FieldDescriptor
from google.protobuf.internal.enum_type_wrapper import EnumTypeWrapper as _EnumTypeWrapper
from google.protobuf.message import Message as __Message

__all__ = [
    "LedgerOffset",
]

class LedgerOffset(__Message):
    absolute: str
    boundary: _typing.Literal[0, 1]
    def __init__(self, *, absolute: _typing.Optional[str] = ..., boundary: _typing.Optional[_typing.Literal[0, 1]] = ...): ...
    def __eq__(self, other_msg: _typing.Optional[_typing.Any]) -> bool: ...
    def __str__(self) -> str: ...
    def __unicode__(self) -> str: ...
    def MergeFrom(self, other_msg: LedgerOffset) -> None: ...
    def Clear(self) -> None: ...
    def SetInParent(self) -> None: ...
    def IsInitialized(self) -> bool: ...
    def MergeFromString(self, serialized: bytes) -> int: ...
    def SerializeToString(self, *, deterministic: bool = ...) -> bytes: ...
    def SerializePartialToString(self, *, deterministic: bool = ...) -> bytes: ...
    def ListFields(self) -> _typing.Sequence[_typing.Tuple[__FieldDescriptor, _typing.Any]]: ...
    def HasField(self, field_name: _typing.Literal["value", "absolute", "boundary"]) -> bool: ...
    def ClearField(self, field_name: _typing.Literal["value", "absolute", "boundary"]) -> None: ...
    def WhichOneof(self, oneof_group: _typing.Literal["value"]) -> _typing.Literal[None, "absolute", "boundary"]: ...
    def HasExtension(self, extension_handle: _typing.Any) -> bool: ...
    def ClearExtension(self, extension_handle: _typing.Any) -> None: ...
    def UnknownFields(self) -> _typing.Any: ...
    def DiscardUnknownFields(self) -> None: ...
    def ByteSize(self) -> int: ...
    def _SetListener(self, message_listener: _typing.Any) -> None: ...

    class LedgerBoundary(_EnumTypeWrapper):
        @_typing.overload
        def Name(self, number: _typing.Literal[0]) -> _typing.Literal["LEDGER_BEGIN"]: ...
        @_typing.overload
        def Name(self, number: _typing.Literal[1]) -> _typing.Literal["LEDGER_END"]: ...
        @_typing.overload
        def Value(self, name: _typing.Literal["LEDGER_BEGIN"]) -> _typing.Literal[0]: ...
        @_typing.overload
        def Value(self, name: _typing.Literal["LEDGER_END"]) -> _typing.Literal[1]: ...

    LEDGER_BEGIN: _typing.ClassVar[_typing.Literal[0]] = ...
    LEDGER_END: _typing.ClassVar[_typing.Literal[1]] = ...
