#!/usr/bin/env bash
# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

export PATH=$PATH:~/.daml/bin

if ! command -v daml &>/dev/null ; then
    curl -sSL https://get.daml.com/ | sh
fi

exec -- daml install $@
