#!/usr/bin/env bash
# Copyright (c) 2017-2021 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

java_dir="$HOME/.java"
export PATH="$PATH:$java_dir/bin"

url=https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz

if ! command -v java &>/dev/null ; then
    mkdir -p "${java_dir}"
    curl -sSL "${url}" -o "${java_dir}/java.tar.gz"
    (cd "${java_dir}" && tar xfz java.tar.gz)
    rm "${java_dir}/java.tar.gz"
fi
