# Copyright (c) 2017-2025 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# fmt: off
# isort: skip_file
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bft_ordering_service_pb2 as com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/digitalasset/canton/synchronizer/sequencing/sequencer/bftordering/v30/bft_ordering_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BftOrderingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService/Ping',
                request_serializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingRequest.SerializeToString,
                response_deserializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Receive = channel.stream_stream(
                '/com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService/Receive',
                request_serializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveRequest.SerializeToString,
                response_deserializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveResponse.FromString,
                _registered_method=True)


class BftOrderingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Receive(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BftOrderingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingRequest.FromString,
                    response_serializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingResponse.SerializeToString,
            ),
            'Receive': grpc.stream_stream_rpc_method_handler(
                    servicer.Receive,
                    request_deserializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveRequest.FromString,
                    response_serializer=com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BftOrderingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService/Ping',
            com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingRequest.SerializeToString,
            com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Receive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.digitalasset.canton.synchronizer.sequencing.sequencer.bftordering.v30.BftOrderingService/Receive',
            com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveRequest.SerializeToString,
            com_dot_digitalasset_dot_canton_dot_synchronizer_dot_sequencing_dot_sequencer_dot_bftordering_dot_v30_dot_bft__ordering__service__pb2.BftOrderingServiceReceiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
