# Copyright (c) 2017-2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
name: build-on-gha
on: push

defaults:
  run:
    shell: bash -euo pipefail -c "source nix.source && exec bash {0}"

permissions:
  contents: read
jobs:
  python-build:
    runs-on: digital-asset-dazl-client
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix
      - run: |
          poetry config virtualenvs.in-project true
          poetry env use python${{ matrix.python-version }}
          make python-deps
      - name: Format
        run: make python-format-test
      - name: Typecheck
        run: make python-typecheck
      - run: make python-unit-test
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: target/test-results

  go-build:
    runs-on: digital-asset-dazl-client
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix
      - run: go build ./...

  blackduck-gha:
    runs-on: digital-asset-dazl-client
    env:
      BLACKDUCK_HUBDETECT_TOKEN: ${{ secrets.DA_BLACKDUCK }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix
      - run: make build
      - name: BlackDuck Detect
        env:
          SCAN_MODE: ${{ github.ref_name == 'main' && 'INTELLIGENT' || 'RAPID' }}
        run: |
          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
            ci-build \
            "${{ github.repository_owner }}_${{ github.event.repository.name }}" \
            "${{ github.ref_name }}" \
            --detect.included.detector.types=POETRY \
            --detect.excluded.detector.types=GO_MOD \
            --detect.tools=DETECTOR \
            --logging.level.com.synopsys.integration=DEBUG \
            --detect.blackduck.scan.mode="$SCAN_MODE" \
            --detect.policy.check.fail.on.severities=MAJOR,CRITICAL,BLOCKER \
            --detect.timeout=600
